# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SLOHacks2018' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SLOHacks2018 

  pod 'Firebase/Core'

  target 'SLOHacks2018Tests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'

  end

  target 'SLOHacks2018UITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'

  end

end
